// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type StatItem struct {
	Label string
	Value string
}

var StatsList = []StatItem{
	{Label: "Subagentes", Value: "12+"},
	{Label: "Paquetes Go", Value: "31"},
	{Label: "Comandos CLI", Value: "30+"},
	{Label: "Lentes Review", Value: "4"},
	{Label: "Plataformas Gateway", Value: "5"},
	{Label: "Providers LLM", Value: "4+"},
}

func Architecture() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"architecture\" class=\"relative py-32 px-6\"><div class=\"bg-glow-orb bg-neon-emerald bottom-0 left-0 opacity-10\"></div><div class=\"max-w-5xl mx-auto relative z-10\"><div class=\"text-center mb-16\"><h2 class=\"text-4xl md:text-5xl font-extrabold mb-4\"><span class=\"text-gradient-cyan\">Hexagonal</span> Architecture</h2><p class=\"text-text-secondary text-lg max-w-2xl mx-auto\">Puertos y adaptadores. 31 paquetes Go. Un solo binario.</p></div><!-- Stats Grid --><div class=\"grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-16\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, stat := range StatsList {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"glass-card rounded-xl p-5 text-center border border-border-subtle hover:border-border-neon-cyan/30 hover:bg-bg-card-hover transition-all duration-300\"><div class=\"text-2xl font-extrabold text-gradient mb-1\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(stat.Value)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/components/architecture.templ`, Line: 35, Col: 74}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"text-xs text-text-muted font-mono\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(stat.Label)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/components/architecture.templ`, Line: 36, Col: 65}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><!-- Architecture Diagram --><div class=\"glass-card rounded-2xl p-6 sm:p-8 border border-border-subtle overflow-hidden shadow-2xl\"><div class=\"flex items-center justify-between mb-4 pb-3 border-b border-border-subtle\"><span class=\"text-xs font-mono text-neon-cyan flex items-center gap-2\"><span class=\"w-2 h-2 rounded-full bg-neon-cyan animate-pulse\"></span> Architecture Map</span> <span class=\"text-xs font-mono text-text-muted\">Single Binary Topology</span></div><pre class=\"font-mono text-xs sm:text-xs leading-relaxed text-text-secondary overflow-x-auto p-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(`┌──────────────────────────────────────────────────────────┐
│                     GAIA (single binary)                    │
│                                                            │
│  ┌─────────────────────────────────────────────────┐      │
│  │  ORCHESTRATOR — Main Agent Loop                 │      │
│  │  • Think → Act → Learn → Persist                │      │
│  │  • Delegates to specialized subagents           │      │
│  │  • Synthesizes results, never does the work     │      │
│  │  • Progressive skill index (~3k tokens)         │      │
│  │  • Knowledge graph recall per turn              │      │
│  └─────────────────────────────────────────────────┘      │
│                           │                                │
│  ┌────────────────────────┼────────────────────────┐      │
│  │  SUBAGENT SYSTEM       │  Autonomous & Specialized│      │
│  │                        │                         │      │
│  │  ┌─────────┐┌────────┐┌────────┐┌──────────┐   │      │
│  │  │Explorer ││Proposer││Specifier││ Designer  │   │      │
│  │  └─────────┘└────────┘└────────┘└──────────┘   │      │
│  │  ┌─────────┐┌────────┐┌────────┐┌──────────┐   │      │
│  │  │ Planner ││Implement││Verifier││ Reviewer  │   │      │
│  │  └─────────┘└────────┘└────────┘└──────────┘   │      │
│  │  ┌─────────┐┌────────┐┌────────┐┌──────────┐   │      │
│  │  │ Learner ││Research││Archiver││ Debugger  │   │      │
│  │  └─────────┘└────────┘└────────┘└──────────┘   │      │
│  └─────────────────────────────────────────────────┘      │
│                           │                                │
│  ┌─────────────────────────────────────────────────┐      │
│  │  INFRASTRUCTURE                                  │      │
│  │  ┌────────┐┌──────────┐┌──────┐┌───────────┐   │      │
│  │  │LLM     ││Tool Exec ││Memory││Knowledge   │   │      │
│  │  │Provider││Engine    ││Engram││Graph Recall│   │      │
│  │  └────────┘└──────────┘└──────┘└───────────┘   │      │
│  │  ┌────────┐┌──────────┐┌──────┐┌───────────┐   │      │
│  │  │TUI     ││Desktop   ││MCP   ││Skills     │   │      │
│  │  │BubbleTea││Wails     ││Client││Loader     │   │      │
│  │  └────────┘└──────────┘└──────┘└───────────┘   │      │
│  └─────────────────────────────────────────────────┘      │
└──────────────────────────────────────────────────────────┘`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/components/architecture.templ`, Line: 88, Col: 181}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</pre></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
