// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type StatItem struct {
	Label string
	Value string
}

var StatsList = []StatItem{
	{Label: "Subagents", Value: "12+"},
	{Label: "Go Packages", Value: "33"},
	{Label: "CLI Commands", Value: "30+"},
	{Label: "LLM Providers", Value: "19"},
	{Label: "UI Interfaces", Value: "3"},
	{Label: "Gateway Platforms", Value: "5"},
}

func Architecture() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"architecture\" class=\"relative py-32 px-6\"><div class=\"bg-glow-orb bg-neon-emerald bottom-0 left-0 opacity-10\"></div><div class=\"max-w-5xl mx-auto relative z-10\"><div class=\"text-center mb-16\"><h2 class=\"text-4xl md:text-5xl font-extrabold mb-4\"><span class=\"text-gradient-cyan\">Hexagonal</span> Architecture &amp; SDD</h2><p class=\"text-text-secondary text-lg max-w-2xl mx-auto\">Ports and adapters. 8-phase structured SDD pipeline. 33 Go packages in a single binary.</p></div><!-- Stats Grid --><div class=\"grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-16\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, stat := range StatsList {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"glass-card rounded-xl p-5 text-center border border-border-subtle hover:border-border-neon-cyan/30 hover:bg-bg-card-hover transition-all duration-300\"><div class=\"text-2xl font-extrabold text-gradient mb-1\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(stat.Value)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/components/architecture.templ`, Line: 35, Col: 74}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"text-xs text-text-muted font-mono\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(stat.Label)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/components/architecture.templ`, Line: 36, Col: 65}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><!-- Visual Mermaid Diagram 1: Hexagonal Architecture --><div class=\"glass-card rounded-2xl p-6 sm:p-8 border border-border-subtle overflow-hidden shadow-2xl mb-8\"><div class=\"flex items-center justify-between mb-6 pb-3 border-b border-border-subtle\"><span class=\"text-xs font-mono text-neon-cyan flex items-center gap-2\"><span class=\"w-2 h-2 rounded-full bg-neon-cyan animate-pulse\"></span> Hexagonal Architecture Flow</span> <span class=\"text-xs font-mono text-text-muted\">Interactive Ports &amp; Adapters</span></div><div class=\"mermaid flex justify-center py-4 overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(`flowchart TD
    subgraph Core ["GAIA Kernel & Orchestrator"]
        Loop["Main Loop: Think ➔ Act ➔ Learn ➔ Persist"]
        PG["PolicyGuard (Tiers: read / sandbox / full)"]
        KG["Knowledge Graph (User, Language, Project)"]
        Loop <--> PG
        Loop <--> KG
    end

    subgraph Subagents ["Specialized Subagents (@name)"]
        direction TB
        SDD_A["SDD: Explorer · Proposer · Specifier · Designer · Planner · Implementer · Verifier · Archiver"]
        OD_A["On-Demand: Reviewer (4 Lenses) · Debugger · Researcher"]
        BG_A["Background: Learner (Skill Synthesis) · Dynamic Subagents"]
    end

    subgraph Adapters ["Adapters & Interfaces"]
        direction LR
        LLM["19 LLM Providers & Pool"]
        UI["Cyberpunk TUI · Web Dashboard · Desktop"]
        GW["Gateways: Telegram · Discord · Slack · WhatsApp"]
    end

    Core <==> Subagents
    Core <==> Adapters
`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/components/architecture.templ`, Line: 76, Col: 1}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div></div><!-- Visual Mermaid Diagram 2: SDD 8-Stage Pipeline --><div class=\"glass-card rounded-2xl p-6 sm:p-8 border border-border-subtle overflow-hidden shadow-2xl\"><div class=\"flex items-center justify-between mb-6 pb-3 border-b border-border-subtle\"><span class=\"text-xs font-mono text-neon-emerald flex items-center gap-2\"><span class=\"w-2 h-2 rounded-full bg-neon-emerald animate-pulse\"></span> Spec-Driven Development Pipeline</span> <span class=\"text-xs font-mono text-text-muted\">8-Phase Continuous Delivery</span></div><div class=\"mermaid flex justify-center py-4 overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(`flowchart LR
    E["1. Explore\n(@explorer)"] --> P["2. Propose\n(@proposer)"]
    P --> S["3. Spec\n(@specifier)"]
    S --> D["4. Design\n(@designer)"]
    D --> T["5. Tasks\n(@planner)"]
    T --> A["6. Apply\n(@implementer)"]
    A --> V["7. Verify\n(@verifier)"]
    V -- "Pass" --> ARC["8. Archive\n(@archiver)"]
    V -. "Fail / Fix" .-> A
`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/components/architecture.templ`, Line: 99, Col: 1}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
