// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type CodeSnippet struct {
	Label string
	Code  string
}

var SnippetsList = []CodeSnippet{
	{
		Label: "Linux & macOS (Installer)",
		Code:  "curl -fsSL https://raw.githubusercontent.com/SalvucciFacundo/gaia/main/install.sh | bash",
	},
	{
		Label: "Windows (PowerShell)",
		Code:  "iwr -useb https://raw.githubusercontent.com/SalvucciFacundo/gaia/main/install.ps1 | iex",
	},
	{
		Label: "Build from Source",
		Code:  "git clone https://github.com/SalvucciFacundo/gaia.git\ncd gaia\ngo build -o gaia ./cmd/gaia/\n./gaia",
	},
	{
		Label: "Web UI Dashboard",
		Code:  "gaia serve 8080",
	},
	{
		Label: "Docker Backend",
		Code:  "gaia exec \"explain this project\" --backend docker",
	},
	{
		Label: "SSH Remote Backend",
		Code:  "gaia exec \"list files\" --backend ssh://user@server",
	},
}

func QuickStart() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"quickstart\" class=\"relative py-32 px-6\"><div class=\"bg-glow-orb bg-neon-cyan bottom-0 right-0 opacity-10\"></div><div class=\"max-w-5xl mx-auto relative z-10\"><div class=\"text-center mb-16\"><h2 class=\"text-4xl md:text-5xl font-extrabold mb-4\">Get Started in <span class=\"text-gradient-emerald\">Seconds</span></h2><p class=\"text-text-secondary text-lg max-w-2xl mx-auto\">Install instantly with a one-line installer or compile the standalone Go binary from source.</p></div><div class=\"grid md:grid-cols-2 lg:grid-cols-3 gap-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, block := range SnippetsList {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"glass-card rounded-2xl border border-border-subtle overflow-hidden group hover:border-border-neon-emerald/30 transition-all duration-300 flex flex-col justify-between\"><!-- Header --><div class=\"flex items-center justify-between px-5 py-3 border-b border-border-subtle bg-bg-surface/50\"><div class=\"flex items-center gap-2\"><span class=\"w-2.5 h-2.5 rounded-full bg-neon-emerald/60\"></span> <span class=\"text-xs font-mono text-text-muted\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(block.Label)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/components/quickstart.templ`, Line: 56, Col: 69}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.RenderScriptItems(ctx, templ_7745c5c3_Buffer, templ.ComponentScript{Call: "copyCode(this, " + templ.EscapeString(`"`+block.Code+`"`) + ")"})
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<button onclick=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 templ.ComponentScript = templ.ComponentScript{Call: "copyCode(this, " + templ.EscapeString(`"`+block.Code+`"`) + ")"}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3.Call)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" class=\"text-xs font-mono text-text-muted hover:text-neon-cyan transition-colors\">copy</button></div><!-- Code --><pre class=\"p-5 font-mono text-xs sm:text-sm leading-relaxed overflow-x-auto flex-1 flex items-center\"><code class=\"text-text-secondary\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(block.Code)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/components/quickstart.templ`, Line: 69, Col: 20}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</code></pre></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div><!-- First Run Wizard Card --><div class=\"mt-8 glass-card rounded-2xl p-6 sm:p-8 border border-border-subtle shadow-lg\"><div class=\"flex items-start gap-4\"><div class=\"w-10 h-10 rounded-xl bg-neon-cyan/10 border border-neon-cyan/20 flex items-center justify-center flex-shrink-0 text-neon-cyan font-bold text-lg\">1</div><div class=\"flex-1\"><h4 class=\"font-semibold text-text-primary mb-1\">First Run Setup Wizard</h4><p class=\"text-sm text-text-secondary mb-3 leading-relaxed\">On first launch, GAIA automatically starts an interactive terminal setup wizard to configure your preferred LLM provider (or auto-detect local Ollama / Copilot) and install recommended skills for your project stack.</p><div class=\"glass-card rounded-xl p-4 border border-border-subtle font-mono text-xs sm:text-sm\"><span class=\"text-neon-emerald\">$</span> <span class=\"text-text-primary\">gaia</span><br><span class=\"text-text-muted italic\"># Interactive setup wizard starts automatically · Config stored in ~/.gaia/config.yaml</span></div></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
